model: anthropic/claude-3-7-sonnet-20250219
dark-mode: true
read:
  - prompts/
auto-commits: false

# auto-lint: true
# lint-cmd:
  # - "typescript: npm run lint && npm run check"

# auto-test: true
# test-cmd: "typescript: npm run test"
