model: anthropic/claude-3-7-sonnet-20250219
dark-mode: true
read:
  - prompts/typescript-tdd-prompt.md

auto-lint: true
lint-cmd:
  - "npm run lint && npm run check"

auto-test: true
test-cmd: "npm run test"
